- name: cart
  hosts: localhost
  become: yes
  tasks:
  - name: diable and enable nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: add roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: create app folder
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download cart
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/cart.zip
      dest: /tmp/cart.zip

  - name: unarchive cart
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app

  - name: install dependencies
    ansible.builtin.shell: npm install
    args:
      chdir: /app

  - name: copy cart service
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service
      remote_src: yes
  
  - name: perform the reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: enable and start cart
    ansible.builtin.service:
      name: cart
      state: started
      enabled: true 