- name: mysql
  hosts: localhost
  become: yes
  tasks:
  - name: disable mysql
    ansible.builtin.shell: dnf module disable mysql -y
  
  - name: Copy mysql
    ansible.builtin.copy:
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo

  - name: install mysql-community-server
    ansible.builtin.package:
      name: mysql-community-server
      state: present

  - name: start mysqld
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: true

  - name: set password
    ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1