- name: rabbitmq
  hosts: localhost
  become: yes
  tasks:
  - name: curl script 1
    ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash
  
  - name: curl script 2
    ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash
  
  - name: install rabbitmq
    ansible.builtin.package:
      name: rabbitmq-server
      state: present

  - name: start and enable rabbitmq
    ansible.builtin.service:
      name: rabbitmq-server 
      state: started
      enabled: yes

  - name: add roboshop user
    community.rabbitmq.rabbitmq_user:
      user: roboshop
      password: roboshop123

  - name: set permissions to user
    ansible.builtin.shell: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"